### PR TITLE
Fix an issue when crawl stops if site fails on broken .gz compression

### LINKED ISSUE #50: zlib errors are not caught in node-fetch
The whole process fails when zlib bails, which is unexpected in itself as kue should recover.

```
[1458355807536] start - japanpost.jp
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:363:17)
```

https://stackoverflow.com/questions/35439074/how-do-i-catch-zlib-errors-in-node-js suggests to catch errors from the decompressed stream which needs to be done in https://github.com/bitinn/node-fetch/blob/258c036ca75fb35bb0080612f61db6a3945a23ae/index.js#L159

### PR DESCRIPTION
**Pull request by zalun**
Fixes #50 
First - reproduce the error
Then - make the crawl immune to the issue

### CODE REVIEW

**Comment by zalun** [comment]
Currently just reproducing the error -   
```
1) broken sites with a broken gzip should print the error:
     Uncaught Error: incorrect header check
      at Zlib._handle.onerror (zlib.js:363:17)
```

File: test/jobProcessor.js [hunk 1]
```diff
@@ -150,3 +153,66 @@ describe('processUrlJob for a site', () => {
...
+          if (err) {
+            reject(err);
+            return;
+          }
+          resolve(data);
+        });
+      })
+      .then(data => getPort()
+        .then(port => {
+          process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
```
Comment (delapuente) [inline test/jobProcessor.js]: I think you should revert this at some moment in the test. Maybe you could put this in a `before()` clause and restore in the `after()` clause.
